#!/usr/bin/env python3
"""
Generate pair-level expert assets for the low-resource MT MoE experiment.

This repository currently trains Qwen with LLaMA-Factory LoRA configs. The
practical MoE variant here is therefore a routed LoRA-expert setup: one expert
adapter per source->target pair, with inference routing by language pair.

Default experts:
  spa_Latn, ind_Latn, vie_Latn, tha_Thai, tgl_Latn <-> zho_Hans
  spa_Latn, ind_Latn, vie_Latn, tha_Thai, tgl_Latn <-> eng_Latn
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


SOURCE_LANGS = ("spa_Latn", "ind_Latn", "vie_Latn", "tha_Thai", "tgl_Latn")
TARGET_LANGS = ("zho_Hans", "eng_Latn")


@dataclass(frozen=True)
class Expert:
    src_lang: str
    tgt_lang: str

    @property
    def dataset_name(self) -> str:
        return f"nllb_moe_{self.src_lang}_to_{self.tgt_lang}"

    @property
    def file_name(self) -> str:
        return f"multilingual/nllb_moe/nllb_mt_{self.src_lang}__{self.tgt_lang}.jsonl"

    @property
    def adapter_name(self) -> str:
        return f"qwen3_8b_moe_{self.src_lang}_to_{self.tgt_lang}"

    @property
    def config_name(self) -> str:
        return f"llamafactory_{self.adapter_name}.yaml"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def q(s: str) -> str:
    """YAML single-quote a scalar."""
    return "'" + s.replace("'", "''") + "'"


def render_yaml(
    expert: Expert,
    *,
    model_name_or_path: str,
    dataset_dir: str,
    output_root: str,
    cutoff_len: int,
    lora_rank: int,
    batch_size: int,
    grad_accum: int,
    learning_rate: str,
    epochs: float,
    save_steps: int,
    logging_steps: int,
    preprocessing_workers: int,
) -> str:
    output_dir = f"{output_root.rstrip('/')}/{expert.adapter_name}"
    return f"""# Pair-level MoE expert: {expert.src_lang} -> {expert.tgt_lang}
# Generated by scripts/moe/generate_pair_expert_assets.py
# Run with:
#   llamafactory-cli train {expert.config_name}

### model
model_name_or_path: {q(model_name_or_path)}
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: {lora_rank}
lora_target: all

### dataset
dataset_dir: {q(dataset_dir)}
dataset: {expert.dataset_name}
template: qwen
cutoff_len: {cutoff_len}
overwrite_cache: true
preprocessing_num_workers: {preprocessing_workers}

### output
output_dir: {q(output_dir)}
logging_steps: {logging_steps}
save_steps: {save_steps}
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: {batch_size}
gradient_accumulation_steps: {grad_accum}
learning_rate: {learning_rate}
num_train_epochs: {epochs:g}
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
"""


def dataset_info_entry(expert: Expert) -> dict[str, object]:
    return {
        "file_name": expert.file_name,
        "formatting": "alpaca",
        "columns": {
            "prompt": "instruction",
            "query": "input",
            "response": "output",
        },
    }


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate MoE pair-expert LLaMA-Factory assets.")
    p.add_argument("--out-dir", type=Path, default=repo_root() / "training" / "moe_experts")
    p.add_argument(
        "--pairs-config",
        type=Path,
        default=repo_root() / "training" / "moe_pair_limits.json",
        help="Output pairs config for prepare_nllb_for_llamafactory.py.",
    )
    p.add_argument(
        "--dataset-info",
        type=Path,
        default=repo_root() / "training" / "moe_dataset_info.snippet.json",
        help="Output dataset_info snippet to merge into training/data/dataset_info.json.",
    )
    p.add_argument(
        "--llamafactory-dataset-info",
        type=Path,
        default=repo_root() / "training" / "data" / "dataset_info.json",
        help="LLaMA-Factory dataset_info.json to create/update with the expert datasets.",
    )
    p.add_argument(
        "--no-update-llamafactory-dataset-info",
        action="store_true",
        help="Only write the snippet; do not create/update training/data/dataset_info.json.",
    )
    p.add_argument(
        "--router-manifest",
        type=Path,
        default=repo_root() / "training" / "moe_router_manifest.json",
        help="Output language-pair to LoRA adapter routing manifest.",
    )
    p.add_argument("--source-langs", nargs="+", default=list(SOURCE_LANGS))
    p.add_argument("--target-langs", nargs="+", default=list(TARGET_LANGS))
    p.add_argument(
        "--bidirectional",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Generate both low-resource->pivot and pivot->low-resource experts.",
    )
    p.add_argument("--limit", type=int, default=100000)
    p.add_argument(
        "--model-name-or-path",
        default="/root/lowres_new/models/Qwen3-8B_latest",
    )
    p.add_argument("--dataset-dir", default="/root/lowres_new/training/data")
    p.add_argument("--output-root", default="/root/lowres_new/models/Qwen3-8B_moe_pair_experts")
    p.add_argument("--cutoff-len", type=int, default=512)
    p.add_argument("--lora-rank", type=int, default=8)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--gradient-accumulation-steps", type=int, default=8)
    p.add_argument("--learning-rate", default="2.0e-5")
    p.add_argument("--num-train-epochs", type=float, default=1.0)
    p.add_argument("--save-steps", type=int, default=200)
    p.add_argument("--logging-steps", type=int, default=20)
    p.add_argument("--preprocessing-num-workers", type=int, default=4)
    p.add_argument("--dry-run", action="store_true")
    return p


def main() -> int:
    args = build_arg_parser().parse_args()
    expert_pairs: list[tuple[str, str]] = []
    for src in args.source_langs:
        for tgt in args.target_langs:
            if src == tgt:
                continue
            expert_pairs.append((src, tgt))
            if args.bidirectional:
                expert_pairs.append((tgt, src))
    # Preserve order while removing duplicates in case source/target sets overlap.
    expert_pairs = list(dict.fromkeys(expert_pairs))
    experts = [Expert(src, tgt) for src, tgt in expert_pairs]
    if not experts:
        raise SystemExit("No experts requested.")

    pairs_config = {
        "_comment": (
            "MoE pair experts: one LoRA adapter per source->target direction. "
            "Use with scripts/prepare/prepare_nllb_for_llamafactory.py "
            "--pairs-config training/moe_pair_limits.json --export-from-config "
            "--out-subdir multilingual/nllb_moe"
        ),
        "dataset": "nllb",
        "default_split": "train",
        "pairs": [
            {"src_lang": e.src_lang, "tgt_lang": e.tgt_lang, "limit": args.limit}
            for e in experts
        ],
    }
    dataset_info = {e.dataset_name: dataset_info_entry(e) for e in experts}
    router_manifest = {
        "description": "Route each language pair to its dedicated LoRA expert adapter.",
        "base_model": args.model_name_or_path,
        "served_model_name": "qwen3-8b-moe-router",
        "experts": [
            {
                "src_lang": e.src_lang,
                "tgt_lang": e.tgt_lang,
                "dataset": e.dataset_name,
                "adapter_name": e.adapter_name,
                "adapter_path": f"{args.output_root.rstrip('/')}/{e.adapter_name}",
            }
            for e in experts
        ],
    }

    if args.dry_run:
        print(json.dumps(router_manifest, ensure_ascii=False, indent=2))
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for e in experts:
        cfg = render_yaml(
            e,
            model_name_or_path=args.model_name_or_path,
            dataset_dir=args.dataset_dir,
            output_root=args.output_root,
            cutoff_len=args.cutoff_len,
            lora_rank=args.lora_rank,
            batch_size=args.batch_size,
            grad_accum=args.gradient_accumulation_steps,
            learning_rate=args.learning_rate,
            epochs=args.num_train_epochs,
            save_steps=args.save_steps,
            logging_steps=args.logging_steps,
            preprocessing_workers=args.preprocessing_num_workers,
        )
        (args.out_dir / e.config_name).write_text(cfg, encoding="utf-8")

    args.pairs_config.parent.mkdir(parents=True, exist_ok=True)
    args.pairs_config.write_text(json.dumps(pairs_config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.dataset_info.parent.mkdir(parents=True, exist_ok=True)
    args.dataset_info.write_text(json.dumps(dataset_info, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if not args.no_update_llamafactory_dataset_info:
        merged: dict[str, object] = {}
        if args.llamafactory_dataset_info.is_file():
            merged = json.loads(args.llamafactory_dataset_info.read_text(encoding="utf-8"))
            if not isinstance(merged, dict):
                raise SystemExit(f"dataset_info is not a JSON object: {args.llamafactory_dataset_info}")
        merged.update(dataset_info)
        args.llamafactory_dataset_info.parent.mkdir(parents=True, exist_ok=True)
        args.llamafactory_dataset_info.write_text(
            json.dumps(merged, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    args.router_manifest.parent.mkdir(parents=True, exist_ok=True)
    args.router_manifest.write_text(json.dumps(router_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"Generated {len(experts)} expert configs in {args.out_dir}")
    print(f"Wrote pairs config: {args.pairs_config}")
    print(f"Wrote dataset_info snippet: {args.dataset_info}")
    if not args.no_update_llamafactory_dataset_info:
        print(f"Updated LLaMA-Factory dataset_info: {args.llamafactory_dataset_info}")
    print(f"Wrote router manifest: {args.router_manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
